version: "3.7"
services:
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: jira-logger-cli:1.0.0
    container_name: jiralogger-cli
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
