version: "3.7"
services:
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: jira-logger-cli:1.0.0
    container_name: jiralogger-cli
    tty: true
    stdin_open: true
    volumes:
      - .:/home/jiralogger/jiralogger
      - ~/.ssh:/home/jiralogger/.ssh
